# Generated by Django 3.2 on 2024-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_watchlist_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
